---
title: "Situación problema: Ghostbusters"
author:
  - name: "Jessica Dong"
  - name: "Ebony Valadez"
  - name: "Emiliano Guzmán"
  - name: "Rafael Gutiérrez "
date: today
lang: es
abstract: |
 Este proyecto implementa un clasificador Naïve Bayes para categorizar relatos de fenómenos paranormales recopilados de la plataforma Your Ghost Stories en internte. Se construyó una base de datos aplicando web scraping que incluye título, lugar, categoría y descripción de cada historia. Se llevó a cabo un procesamiento de los textos mediante un análisis del lenguaje natural y fueron representados en una matriz basada en la frecuencia de las palabras. Con estos datos se entrenaron y evaluaron clasificadores Naïve Bayes en diferentes escenarios, realizando ajustes de Laplace smoothing, distribución Poisson y validación cruzada. Se pretende que con los resultados sea posible simplificar la clasificación dentro del análisis de textos de manera automatizada, así como plantearlo con diversos enfoques de distintas área.
keywords: ["web scrapping", "clasificador Naïve Bayes","Natural Language Processing", "modelado probabilístico"]

execute:
  echo: false       
  warning: false
  message: false

crossref:
  fig-prefix: "Figura"
  tbl-prefix: "Tabla"
  eq-prefix: "Ecuación"

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo
    code-fold: show
    code-tools: true
    df-print: paged
    math: mathjax
  pdf:
    documentclass: article
    toc: true
    toc-depth: 3
    number-sections: true
    geometry: "margin=1in"
    fig-cap-location: bottom
    tbl-cap-location: top
---


# Introducción

Para lograr un análisis automatizado de texto, es necesario incorporar técnicas de procesamiento de lenguaje natural (NLP), entendido como un campo que “se ocupa de cómo las computadoras entienden, procesan y manipulan los lenguajes humanos, utilizando métodos estadísticos, aprendizaje automático, redes neuronales y minería de texto” (Network of the National Library of Medicine, 2022). En este proyecto, dichas técnicas son aplicadas con el objetivo de clasificar relatos de fenómenos paranormales que fueron obtenidos mediante web scraping del portal Your Ghost Stories e incorporados a una base de datos.

Con los textos recolectados se realizó una matriz basada en las frecuencias de las palabras para así llevar a cabo múltiples entrenamientos de modelos probabilísticos usando el clasificador Naïve Bayes que es de suma utilidad en tareas de minería de texto, así como también se implementaron variantes ajustadas con Laplace smoothing, distribución Poisson y validación cruzada. El objetivo principal del proyecto es predecir la categoría de cada relato con los datos y la base de datos planteada y así analizar cómo diferentes configuraciones del modelo de clasificación afectan el desempeño en escenarios multiclase y binarios y la manera en la que categoriza.

# Metodología

# Aplicación

# Resultados

# Conclusiones

# Referencias

National Network of Libraries of Medicine. (2022, junio). Natural language processing (NLP). NNLM Data Glossary. https://www.nnlm.gov/guides/data-glossary/natural-language-processing